name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Make GoVarnam
        run: |
          git clone https://github.com/varnamproject/govarnam.git govarnam
          cd govarnam
          make
          sudo make install

      - name: Dependencies
        run: |
          sudo apt install ruby-ffi

      - name: Make Schemes
        run: |
          ./build_all_schemes.sh

      - name: Build Packs
        run: |
          sudo ./install_all_schemes.sh
          ./build_all_packs.sh

      - name: Make Language Zips
        run: |
          ./build_zips.sh

      - name: Upload Release Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.zip"
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
